config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]
  resources :relationships, only: [:create, :destroy]

  resources :conversations do
   resources :messages
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :topics do
   resources :comments
   post :confirm, on: :collection
 end
  root 'top#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # topicをパラメータの値から探し出し,topicに紐づくcommentsとしてbuildします。
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました。' }
        format.js { render :index }
      else
        format.html { render :new }
      end
    end
  end

  private
    # ストロングパラメーター
    def comment_params
      params.require(:comment).permit(:topic_id, :content)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment], remote: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= comment.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :topic_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')