config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]
  resources :relationships, only: [:create, :destroy]

  resources :conversations do
   resources :messages
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :topics do
   resources :comments
   post :confirm, on: :collection
 end
  root 'top#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dive20</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Top</a>
        <button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Star
</button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">検索</button>
        </form>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'マイページ', edit_user_registration_path %></li>
          <li><%= link_to 'ホーム'%></li>
          <li><%= link_to 'メッセージ'%></li>
          <li><%= link_to '友達'%></li>
          <li><%= link_to '通知'%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'ページを作成'%></li>
              <li><%= link_to 'ユーザー一覧', users_path if user_signed_in? %></li>
              <li><%= link_to "メッセージ", conversations_path %></li>
              <li role="separator" class="divider"></li>
              <% if user_signed_in? %>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
              <% else %>
              <li><%= link_to 'ログイン', new_user_session_path %></li>
              <li><%= link_to 'サインアップ', new_user_registration_path %></li>
            <% end %>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<%= yield %>

</body>
</html>